services:
    embedding-worker:
      build:
        context: .
      # comment out the "command" if you just want to run the test_input.json
      command: >
        python -u /handler.py --rp_serve_api --rp_api_host=0.0.0.0
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
      environment:
        MODEL_NAMES: "Qwen/Qwen3-Embedding-4B;Qwen/Qwen3-Reranker-4B"
        NVIDIA_VISIBLE_DEVICES: "all"
        HF_HOME: "/runpod-volume"
      volumes:
        - ./data/runpod-volume:/runpod-volume
      ports:
        - "8000:8000"